trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx3072m"

steps:
- task: UseJava@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dmaven.test.failure.ignore=false'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/testng-results.xml'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/surefire-reports'
    artifactName: 'TestNG-Reports'
    publishLocation: 'Container'
